name: CI/CD Pipeline

on:
  push:
    branches:
      - feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t doramar97/nextflix-int:${{ github.sha }} .

    - name: Push Docker image to Docker Hub
      run: docker push doramar97/nextflix-int:${{ github.sha }}

    - name: Checkout Target Repository
      uses: actions/checkout@v3
      with:
          repository: dor-amar/config
          path: infrastructure
          token: ${{ secrets.TOKEN }} 

    # Update the config repo with the new image
    - name: Update Image Version in the related HelmChart values.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
          valueFile: 'netflix/app/deployment.yaml'
          propertyPath: 'spec.template.spec.containers[0].image'
          value: doramar97/nextflix-int:${{ github.sha }}
          repository: dor-amar/config
          branch: main
          targetBranch: main
          message: 'Update Image Version to ${{ github.sha }}'
          token: ${{ secrets.TOKEN }}
          workDir: infrastructure